### ISSUE TITLE
[Question] Why is instance getting null at the disable method?

### ISSUE THREAD

**Issue by Kev575** [Acquized/Aero#2]
Hey,
I have a question. Why is the instance getting null in [Aero.java L37](https://github.com/Acquized/Aero/blob/master/src/main/java/cc/acquized/aero/Aero.java#L37)?
Wouldn't that be done by the Java gc?

Greetings
Kev575

**Comment by Acquized** [comment]
It would be but it is for people that want to shade my Plugin into their Project. As soon they initalized the Project using `((Aero)Bukkit.getPluginManager().getPlugin("Aero")).onEnable()`, they can access it using `Aero.getInstance()`, but when they decide to shutdown the Plugin when there Plugin is not shutdowned (`Aero.getInstance().onDisable`), i don't want that they can access it back using `getInstance()` so any developer won't make a mistake there.

**Comment by Kev575** [comment]
Ahh, that's clever :D
