### ISSUE TITLE
Anti collision feature conflicts with name tag plugin

### ISSUE THREAD

**Issue by idkw** [Acquized/Aero#3]
Hello,

I have tried Aero, the most interesting feature to me was the anti-collision.

Unfortunately it doesn't work when using a name tag plugin such as [NametagEdit](https://www.spigotmc.org/resources/nametagedit.3836/)
The player have a nametag but they can push each other.

Do you think it is possible to integrate Aero with NametagEdit, or better, with your [Nametags](https://www.spigotmc.org/resources/nametags.13119/) plugin to have both the nametag and the anti collision work at the same time ?

Thanks !

**Comment by Acquized** [comment]
Hello, first thanks for reporting this issue. I'm currently  on vacation and won't be able to reply a proper answer until Friday. I will answer again to this issue request on Friday.
